import { Inter } from "next/font/google";
import "./globals.css";
import Menus from "./Menus";
import MultiTabMegaMenu from "@/components/megamenu";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Menus/>
        {children}</body>
    </html>
  );
}
